packages:
  - .
  - src/philasdb.site

onlyBuiltDependencies:
  - esbuild
  - sharp
allowBuilds:
  esbuild: true
  sharp: true
catalog:
  vite-plus: ^0.1.24
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
