
name: Deploy Github Pages

on:
  push:
    branches: [ "main" ]
    paths: [ "src/philasdb.site/**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 11.5.0
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build Website
        run: pnpm build

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@v5
        with:
            name: 'github-pages'
            path: "src/philasdb.site/dist/"
            retention-days: 1
      
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
  
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
